{{ config(materialized='view') }}

-- ============================================================================
-- stg_raw__season
-- ============================================================================
-- Season reference table derived from the source — RAW.season does not exist
-- as a standalone table in the bronze layer. Generated by extracting the
-- distinct values of the season field from RAW.match and deriving all
-- attributes from the season string itself.
--
-- Grain      : one row per unique season across all leagues
-- Row count  : 8 seasons (2008/2009 → 2015/2016)
-- Loaded as  : view (tiny derived table — no storage cost justified)
-- Sources    : EUROPEAN_SOCCER_DATABASE.match (season field only)
-- Filters    : NULL season values are excluded (WHERE on source)
-- Note       : season_id is generated with ROW_NUMBER() ordered by season_name
--              ASC — stable as long as no new seasons are added to the source
-- ============================================================================

WITH source AS (

    -- Extract the distinct season values from RAW.match.
    -- SELECT DISTINCT is intentional — the match table contains one season
    -- value per match row; deduplication is required to produce a reference table.
    -- NULL seasons are excluded upfront to avoid generating a NULL season_id row.
    SELECT DISTINCT season
    FROM {{ source('EUROPEAN_SOCCER_DATABASE', 'match') }}
    WHERE season IS NOT NULL

),

renamed_casted AS (

    -- Derive all season attributes from the season string (e.g. '2015/2016').
    -- season_id  : surrogate PK generated with ROW_NUMBER() ordered by season
    --              ASC — alphabetical order on 'YYYY/YYYY' strings is equivalent
    --              to chronological order, so season_id = 1 is always 2008/2009.
    -- start_year : extracted by splitting on '/' and taking the first part.
    -- end_year   : extracted by splitting on '/' and taking the second part.
    -- Both years are cast to INTEGER for use in downstream window function
    -- ORDER BY clauses (e.g. LAG() in fct_team_evolution).
    SELECT
        ROW_NUMBER() OVER (ORDER BY season)         AS season_id,    -- Surrogate PK (1 = 2008/2009)
        season                                      AS season_name,  -- Season label (e.g. 2015/2016)
        SPLIT_PART(season, '/', 1)::INTEGER         AS start_year,   -- Four-digit start year (e.g. 2015)
        SPLIT_PART(season, '/', 2)::INTEGER         AS end_year      -- Four-digit end year (e.g. 2016)
    FROM source

)

SELECT * FROM renamed_casted